<?php

return [
        "dashboard" => 'dashboard',
        'advs' => 'ad-management',
        'cats'=> 'ad-management',
        'customfields'=> 'ad-management',
        'dopings'=> 'ad-management',
        'users'=> 'users',
        'profile'=> 'users',
        'messages'=> 'apps',
        'orders'=> 'apps',
        'favs'=> 'apps',
        'files'=> 'apps',
        'complaints'=> 'apps',
        'comments'=> 'apps',
        'notifications'=> 'apps',
        'pushnotifications'=> 'apps',
        'store'=> 'apps',
        'coupon'=> 'apps',
        'packages'=> 'apps',
        'carts'=> 'apps',
        'posts'=> 'cms',
        'pages'=> 'cms',
        'slider'=> 'cms',
        'navigation'=> 'cms',
        'settings'=> 'settings',
        'api'=> 'settings',
        'locations'=> 'settings',
        'blocks'=> 'settings',
        'site'=> 'site-management',
        'subscriptions'=> 'site-management',
        'jenkins'=> 'site-management',
        'cwp'=> 'site-management',
        'satis'=> 'site-management',
];